<ul class="menu_sidebar">
	<li><span>HTML</span>
		<ul>
			<li>HTML</li>
			<li>JAVASCRIPT</li>
			<li>PHP</li>
		</ul>
	</li>
	<li><span>JAVASCRIPT</span>
		<ul>
			<li>HTML</li>
			<li>JAVASCRIPT</li>
			<li>PHP</li>
		</ul>
	</li>
	<li><span>PHP</span>
		<ul>
			<li>HTML</li>
			<li>JAVASCRIPT</li>
			<li>PHP</li>
		</ul>
	</li>
</ul>